FROM python:3.11-alpine

WORKDIR /app

COPY main.py /app/main.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["flask", "--app", "main", "run", "--host=0.0.0.0", "--port=8000"]
